[FE] [35] task 생성 모달 - API 연결
boostcampwm-2022/web19-Boostart pull request #111
Opened 2022-11-29 12:16 UTC by high2092

## 요약
이제 UI를 통해 task를 생성할 수 있습니다.

## 작업 내용
1. API 연결
2. 컴포넌트 이동
  - `TaskModal`
  - `NewTaskButton`

## 테스트 방법
1. 로그인을 완료하세요
2. FAB를 눌러 태스크 모달을 여세요.
3. 제목, 태그, 시작 시각, 종료 시각을 입력하고 `NEW TASK!` 버튼을 누르세요.
4. 생성한 태스크가 화면에 표시됩니다.

2022-11-29 13:48 UTC, ParkKyungChan commented on client/src/components/MainContainer/Log.tsx
> +        return { content, date, done, endedAt: ended_at, idx, importance, lat, lng, startedAt: started_at, tagIdx: tag_idx, title, userIdx: user_idx, isPublic };
이부분도 DB에서는 쿼리 as~~로 FE보다는 큰 차이없이 수정할 수 있으니 나중에 API 고치고 깔끔하게 정리하면 좋을것같습니다

2022-11-29 14:14 UTC, ParkKyungChan requested changes
지금은 모든 옵션을 각각의 상태로 관리하고 옵션이 바뀔때마다 상태와 함께 bodyform도 바꿔주는것같은데요, 옵션의 상태를 바로 bodyform으로 바꿔줄 수 있는 형태로 하나의 상태로 관리하고 한 옵션의 상태가 변하면 그 옵션의 키에 접근해서 변화시키는 방식으로 상태관리를 하고 task를 생성할 때 상태 그대로 body로 만들어서 보내는게 어떨까 하는 생각이 듭니다. 
물론 제가 로직을 잘못이해하고있는걸수도 있지만.. 내일 아침에 얘기해봐요!

2022-11-29 14:14 UTC, ParkKyungChan commented on client/src/components/TaskModal/TaskModal.tsx
>    const { getMonth, getDate } = useCurrentDate();
같은 훅에서 나온거 한줄로 묶어도 될거같아요!

2022-11-29 14:14 UTC, ParkKyungChan commented on client/src/components/TaskModal/TaskModal.tsx
> +              <input {...register('location')} hidden={true} />
여기는 어떤부분인가요?

2022-11-30 04:19 UTC, high2092 commented
상태로 관리하고 있는 것들은 input 이외의 컴포넌트에서 인터페이스가 일어나는 부분들입니다.
`react-hook-form`을 사용하지 않을 경우 모든 폼 요소에 대해 상태를 만들어야 하는데, 그렇게 하기보다는
보이지 않는 hidden input을 일부 추가하고 `react-hook-form`을 사용하는 편이 더 나을 것이라고 생각했습니다.

상태와 input value 간의 동기화 시점에 대해서는 고민해보겠습니다.

2022-11-30 04:22 UTC, mikaniz approved these changes
수고하셨습니다~~~

2022-11-30 07:05 UTC, ParkKyungChan approved these changes

2022-11-30 07:13 UTC, merged