[FE] [57] 태스크 모달 버그 수정
boostcampwm-2022/web19-Boostart pull request #137
Opened 2022-12-03 04:34 UTC by high2092

## 요약
- 태그 목록, 태그 input focus 여부를 모달에서 관리하도록 수정
- tab 키를 통해 태그 input이 focus 되었을 때 자동완성 리스트가 렌더링되지 않던 문제 해결

## 테스트 방법
1. 로그인을 완료하세요.
2. 태스크 FAB를 누르세요.
3. 태그를 등록하세요.
4. 라벨을 등록, 해제하면서 등록했던 태그가 깜빡이는지 확인하세요.

## 관련 Task
- [53] 태스크 모달 내 깜빡임 현상 → 해결

## 비고
- 이제 태그 목록이 로그 컴포넌트에서부터 props로 전달됩니다.

2022-12-04 08:52 UTC, ParkKyungChan requested changes

2022-12-04 08:52 UTC, ParkKyungChan commented on client/src/components/TaskModal/TaskModal.tsx
> +            <Row title="태그" content={<TagInput tagIdx={tagIdx} setTagIdx={setTagIdx} tagList={tagList} fetchTagList={fetchTagList} isTagInputFocused={isTagInputFocused} setIsTagInputFocused={setIsTag
우선 문제를 해결하기 위해 노력해주셔서 감사드리고 고생하셨습니다!
그런데 Props가 너무 많으니 Row 라는 공통컴포넌트로 추상화한 목적이 잘 이뤄진건지 잘 모르겠네요..
다른 Row 컴포넌트가 모두 이렇게 상태관리 메소드등을 다 넘겨주는게 아니다보니 공통화도 잘 되지 않는 느낌입니다.
Row로 통일 시키기 위한게 목적이 된건 아닌가 하는 생각이 듭니다.
모작님이 보기엔 어떤지 모작님 포함해서 다른분들 의견을 들어보고싶습니다.

2022-12-04 09:42 UTC, high2092 commented on client/src/components/TaskModal/TaskModal.tsx
> +            <Row title="태그" content={<TagInput tagIdx={tagIdx} setTagIdx={setTagIdx} tagList={tagList} fetchTagList={fetchTagList} isTagInputFocused={isTagInputFocused} setIsTagInputFocused={setIsTag
props가 많은 건 TagInput 컴포넌트입니다. 다시 읽어보신 후 얘기 나누면 좋을 것 같아요
##### +그리고 props가 많은 것이 추상화를 할지 말지 결정하는 데 있어 크게 중요한 부분은 아니라고 생각합니다.

2022-12-04 09:47 UTC, high2092 commented on client/src/components/TaskModal/TaskModal.tsx
> +            <Row title="태그" content={<TagInput tagIdx={tagIdx} setTagIdx={setTagIdx} tagList={tagList} fetchTagList={fetchTagList} isTagInputFocused={isTagInputFocused} setIsTagInputFocused={setIsTag
다만 저도 상태 관련 로직을 props로 전달하는 게 썩 좋은 방법은 아닌 것 같다고 생각해,
추상화를 풀어헤치는 건 컴포넌트 최초 작성자 분과 같이 얘기를 나눠보면 좋을 것 같습니다.

2022-12-05 01:45 UTC, ParkKyungChan approved these changes

2022-12-05 04:00 UTC, mikaniz approved these changes
수고하셨습니다~

2022-12-05 04:06 UTC, merged