Feature/label patch/69
boostcampwm-2022/web19-Boostart pull request #156
Opened 2022-12-06 10:17 UTC by high2092

## 요약
라벨의 색상, 이름을 수정하는 API입니다.

## 테스트 방법
1. 로그인을 완료하세요
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```js
fetch(`http://localhost:8080/api/v1/label/${labelIdx}`, {
    method: 'PATCH',
    credentials: 'include',
    headers: {
        'Content-Type': 'application/json',
    },
    body: JSON.stringify({
        title: 'zz',
        color: '#aaffff',
    }),
});
```
3. DB에 반영됐는지 확인하세요.

2022-12-06 13:14 UTC, ParkKyungChan requested changes
설명에는 API인데 FE쪽 컴포넌트까지 다 들어가있네요
의도된 범위의 PR이 맞는지 확인부탁드려요~

2022-12-06 17:02 UTC, mikaniz requested changes
확인하시고 수정 부탁드립니다!

2022-12-06 17:02 UTC, mikaniz commented on server/src/api/label.ts
> +  const { title, color } = req.body;
`title`과 `color` 둘 다 입력되지 않은 경우에는 서버 에러가 발생하네요! 둘 다 입력되지 않은 경우에 대한 예외 처리가 필요할 것 같습니다~~

2022-12-07 03:56 UTC, high2092 commented
https://github.com/boostcampwm-2022/web19-Boostart/pull/161 주신 피드백 반영해 새 PR을 올렸습니다. 확인하시면 해당 PR은 닫겠습니다.

2022-12-07 06:46 UTC, closed without merging