[BE] [96] 알림 API 작성
boostcampwm-2022/web19-Boostart pull request #207
Opened 2022-12-10 10:27 UTC by high2092

## 요약
- 기본적인 알림 조회 API 작성

2022-12-10 15:50 UTC, mikaniz requested changes

2022-12-10 15:50 UTC, mikaniz commented on server/src/api/alarm.ts
> +export const alarmRouter = Router();
형식을 통일하면 좋을 것 같아서
```ts
const router = Router();
생략
export default router;
```
로 하고
`/api/index.ts`에서도
```ts
import alarmRouter from './alarm';
```
으로 하면 좋을 것 같습니다~~

2022-12-10 15:53 UTC, mikaniz commented
그리고 `alarm` 테이블에서 `status`는 읽음 상태를 나타내는 게 맞나요?
알림의 경우 사용자가 알림을 읽었다면 데이터를 삭제해도 좋을 것 같은데 어떻게 생각하시는지 궁금합니다~~

2022-12-11 05:13 UTC, high2092 commented on server/src/api/alarm.ts
> +export const alarmRouter = Router();
default export 는 부작용이 있을 수 있다고 들었습니다.
다른 라우터를 named export하도록 바꾸는 것은 어려울까요?

2022-12-11 05:16 UTC, high2092 commented
> 그리고 `alarm` 테이블에서 `status`는 읽음 상태를 나타내는 게 맞나요?
> 알림의 경우 사용자가 알림을 읽었다면 데이터를 삭제해도 좋을 것 같은데 어떻게 생각하시는지 궁금합니다~~

저는 DB 성능에 이슈가 발생하지 않는다면 읽었더라도 가지고 있어도 괜찮다고 생각합니다! (soft delete)
→ 사용자에게 읽음, 읽지 않음 상태를 포함해 보내줄 수 있는 가능성도 생기기 때문에

2022-12-11 16:41 UTC, sooyeon73 approved these changes
주말인데 수고많으셨습니다!!

2022-12-11 16:54 UTC, mikaniz commented on server/src/api/alarm.ts
> +export const alarmRouter = Router();
넵! 지금 코드에서는 영향이 없을 것 같긴 하지만 tree-shaking 면에서 named export 방식이 좋을 것 같네요~~
어차피 지금 MVC 구조로 리팩토링 진행하면서 Controller 파일에서 정의한 함수를 모두 named export 하고 아래와 같은 방식으로 사용하고 있어서 리팩토링 브랜치에서 함께 바꾸도록 하겠습니다~
`import * as Controller from '../controller`

2022-12-11 16:54 UTC, mikaniz approved these changes

2022-12-11 19:01 UTC, merged