[FE/BE] 프로필 사진 업로드 기능
boostcampwm-2022/web19-Boostart pull request #64
Opened 2022-11-22 08:04 UTC by high2092

## 요약
- 회원가입 페이지에서 업로드한 파일이 서버 컴퓨터에 파일 형태로 저장됩니다.
## 작동 화면
[c01262e8-2418-4c99-a9e6-0a984491e038.webm](https://user-images.githubusercontent.com/55306894/203258581-c7b427fd-03f7-445c-927f-1554bdb2576c.webm)

## 작업 내용
1. API 수정
2. 클라이언트에서 회원가입 요청을 보내는 코드 수정

2022-11-22 09:23 UTC, sujinleeme commented
제목에 티켓번호 추가해주세요. 테스트 어떻게 해야하는지도 설명해주세요.

2022-11-22 09:55 UTC, ParkKyungChan requested changes

2022-11-22 09:55 UTC, ParkKyungChan commented on client/src/components/SignupMenu/SignupMenu.tsx
> +  const formData = new FormData();
명확성을 위해 signupData 혹은 signupFromData로 수정하면 어떨까요?

2022-11-22 09:55 UTC, ParkKyungChan commented on client/src/components/SignupMenu/SignupMenu.tsx
> +interface SignupFormSubmit {
interface 선언은 상단에 있는것이 보기 좋은것같네요

2022-11-22 09:55 UTC, ParkKyungChan commented on client/src/components/SignupMenu/SignupMenu.tsx
> +interface SignupFormSubmit {
그리고 SignupFormSubmit으로 동사로 끝나는것보다 SignupSubmitForm이 자연스러워보입니다

2022-11-22 09:55 UTC, ParkKyungChan commented on server/src/api/auth.ts
> +router.post('/signup', async (req: any, res) => {
any 말고 express.Request 하면 오류가 나나요?

2022-11-22 11:23 UTC, sooyeon73 approved these changes
이미지가 포함된 POST 요청은 모든 데이터를 FormData로 묶어서 보내줘야만 하는 건지 궁금합니다 !

2022-11-22 11:51 UTC, high2092 commented
> @sooyeon73 
이미지가 포함된 POST 요청은 모든 데이터를 FormData로 묶어서 보내줘야만 하는 건지 궁금합니다 !

스크립트로 보내려면 `FormData`로 포장해서 보내줘야 하는 것 같습니다.
`FormData` 객체를 사용하지 않고 이미지가 포함된 양식을 제출하려면 다음과 같이 순수 html로 작성된 폼을 사용해야 합니다.
```
<form action="/home/uploadfiles" method="post" enctype="multipart/form-data">
    파일명 : <input type="file" name="myfile">
    <button type="submit">제출하기</button>
</form>
```

2022-11-22 12:15 UTC, mikaniz approved these changes

2022-11-23 03:38 UTC, ParkKyungChan approved these changes

2022-11-23 04:02 UTC, merged