[FE] [4-1] 메인 화면 우측 Drawer 컴포넌트
boostcampwm-2022/web19-Boostart pull request #73
Opened 2022-11-23 05:58 UTC by high2092

## 요약

## 작동 화면
없다면 생략

## 작업 내용
1. 

## 관련 Issue
- 

## 비고

2022-11-24 12:31 UTC, sooyeon73 approved these changes
수고하셨습니다!

2022-11-24 12:31 UTC, sooyeon73 commented on client/src/components/Drawer/Drawer.style.ts
> +`;
아이콘의 경우 react-icons 라이브러리를 사용을 고려해보시는 것도 좋을 것 같아요~
https://react-icons.github.io/react-icons/search?q=pencil

2022-11-24 12:31 UTC, sooyeon73 commented on client/src/components/Drawer/Drawer.tsx
> +  );
해당 컴포넌트의 내용을 작동화면에 반영시켜 줬다면 더 좋을 거 같네요

2022-11-24 12:31 UTC, sooyeon73 commented on client/src/components/Drawer/Drawer.tsx
> +          <ReceivedFriendRequest userId={userId} username={username} profileImg={profileImg} />
map으로 렌더링하는 컴포넌트에 key 값을 추가하면 좋을 것 같습니다

2022-11-24 12:31 UTC, sooyeon73 commented on client/src/components/Drawer/Modal.tsx
> +export default Modal;
저도 시간나면 모달 컴포넌트 사용해보도록 해보겠습니다!

2022-11-24 12:31 UTC, sooyeon73 commented on client/src/components/TopBar/TopBar.tsx
> +        <S.MenuIcon src="./menu.svg" onClick={handleMenuClick} />
MenuIcon style에 cursor:pointer 값 넣어주면 더 좋을 거 같습니답

2022-11-24 14:23 UTC, high2092 commented on client/src/components/Drawer/Drawer.tsx
> +  );
바빠서 녹화를 못했네요.. 😢 다음엔 최신 상태의 테스트 영상을 올릴 수 있도록 노력하겠읍니다

2022-11-25 02:49 UTC, ParkKyungChan requested changes

2022-11-25 02:49 UTC, ParkKyungChan commented on client/src/components/Drawer/Drawer.style.ts
> +export const PROFILE_EDIT_FORM_WIDTH = '40rem';
상수도 외부에서 사용하나요? 전부 export하셔서 질문드립니다.

2022-11-25 02:49 UTC, ParkKyungChan commented on client/src/components/Drawer/Drawer.tsx
> +    alert('서버에 로그아웃하겠다고 알릴게요');
멘트를 일상체로 수정해주세요 ㅎㅎ
개발자체 말고 ㅎㅎㅎ

2022-11-25 02:49 UTC, ParkKyungChan commented on client/src/components/Drawer/Drawer.tsx
> +    alert(`${userId} 님의 친구 요청을 거절하겠다고 서버에 알릴게요.`);
여기도 서버에 알릴께요 말고 수락하시겠습니까? 내지 수락할께요 정도로 바꾸는게 좋겠네요

2022-11-25 02:49 UTC, ParkKyungChan commented on client/src/components/Drawer/Drawer.tsx
> +          <S.ProfileImage padding="2rem" size="10rem" src="https://avatars.githubusercontent.com/u/55306894?s=80&u=aedb7854f1fd10d8eb6dc1272f1583dbb255f5b8&v=4" />
padding이나 size는 통일되어야할것같은데 props로 말고 styled에 고정시켜두는게 좋을것같아요
만약 다른 컴포넌트에서의 재사용성을 고려한것이라면 공통으로 쓸수 있는 style 파일을 만들어서 거기 두는게 좋을거같아요

2022-11-25 06:22 UTC, high2092 commented on client/src/components/Drawer/Drawer.style.ts
> +export const PROFILE_EDIT_FORM_WIDTH = '40rem';
[`cc9b428`](https://github.com/boostcampwm-2022/web19-Boostart/pull/73/commits/cc9b4281db3ea99235d8acce17831859d70f480f#diff-3a5b7585798623f5ced4283c3c224691d3fa61587b8e1607ffc51c44c2541d26R40)에서 사용되었던 레거시를 깜빡하고 지우지 못한 것 같습니다.
피드백 반영하여 불필요한 `export` 문은 삭제하도록 하겠습니다. 감사합니다.

2022-11-25 06:22 UTC, high2092 commented on client/src/components/Drawer/Drawer.tsx
> +    alert('서버에 로그아웃하겠다고 알릴게요');
해당 멘트는 디버그 용도로 작성됐던 것이며, API 연결 시 삭제 또는 수정할 예정입니다.

2022-11-25 06:22 UTC, high2092 commented on client/src/components/Drawer/Drawer.tsx
> +    alert(`${userId} 님의 친구 요청을 거절하겠다고 서버에 알릴게요.`);
해당 멘트는 디버그 용도로 작성됐던 것이며, API 연결 시 삭제 또는 수정할 예정입니다.

2022-11-25 06:22 UTC, high2092 commented on client/src/components/Drawer/Drawer.tsx
> +          <S.ProfileImage padding="2rem" size="10rem" src="https://avatars.githubusercontent.com/u/55306894?s=80&u=aedb7854f1fd10d8eb6dc1272f1583dbb255f5b8&v=4" />
해당 컴포넌트 내에서도 `S.ProfileImage`가 재사용되고 있습니다. [1](https://github.com/boostcampwm-2022/web19-Boostart/pull/73/files#diff-3a5b7585798623f5ced4283c3c224691d3fa61587b8e1607ffc51c44c2541d26R42) [2](https://github.com/boostcampwm-2022/web19-Boostart/pull/73/files#diff-1c079f8606cb80c3eb55c786514a20b3b1b7b2d297ccaf9ce1b1778560cbd2b5R140)
저는 다음과 같은 이유로 `props`로 스타일을 조정하는 것은 문제될 일이  아니라고 생각합니다.
- 코드를 이해하는 데 문제가 없다.
- 시맨틱 측면에서 문제가 없다.

> 만약 다른 컴포넌트에서의 재사용성을 고려한것이라면 공통으로 쓸수 있는 style 파일을 만들어서 거기 두는게 좋을거같아요

→ 다른 파일에서도 `S.ProfileImage`가 쓰이게 된다면 그때 공통 변수를 모아 놓는 파일로 옮기면 될 것 같습니다.

<br>

**다만 피드백을 받고 다시 살펴본 결과 [2](https://github.com/boostcampwm-2022/web19-Boostart/pull/73/files#diff-1c079f8606cb80c3eb55c786514a20b3b1b7b2d297ccaf9ce1b1778560cbd2b5R140)와 같이 작성된 형태가 일관성이 없다고 판단해, 모두 [1](https://github.com/boostcampwm-2022/web19-Boostart/pull/73/files#diff-3a5b7585798623f5ced4283c3c224691d3fa61587b8e1607ffc51c44c2541d26R42)의 형태로 수정할 예정입니다.**

감사합니다.

2022-11-26 14:18 UTC, merged