[BE] [18] task 생성 요청 시 body에 필수 요소만 넣어도 동작하도록 수정
boostcampwm-2022/web19-Boostart pull request #89
Opened 2022-11-26 13:40 UTC by high2092

## 요약
task 생성 요청의 body에 일부 요소가 누락되어 있는 경우 해당 요소가 필수가 아님에도 서버가 죽는 에러를 수정하였습니다.
## 작동 화면
![image](https://user-images.githubusercontent.com/55306894/204091754-97cea5b0-a2c6-4e09-937b-db746fe5f47a.png)

## 테스트 방법
1. 로그인을 완료하세요.
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/task', {
  method: 'post',
  credentials: 'include',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    title: '낮잠',
    date: '2022-11-22',
  }),
}).then((res) => {
  if (res.ok) console.log('GOOD');
});
```
3. 콘솔에 `GOOD`이 출력되는지 확인하세요.

2022-11-27 10:16 UTC, ParkKyungChan requested changes
일단 줄일수있으면 반복되는 부분은 줄이는것이 좋다는것에는 동의하시겠지만 현실적인 문제가 있을시 코멘트 주시면 같이 해결해보거나 이대로 approve 하겠습니다.

2022-11-27 10:16 UTC, ParkKyungChan commented on server/src/api/task.ts
> +  if (!validateLabels(labels)) labels = [];
수고하셨습니다 꼼꼼하게 다 검증해주는거 좋네요!
굳이 피드백 하자면 뭔가 반복되는 부분을 줄이면 좋을것같다는 생각이 드네요.
default값을 상수화해두고 key value 값을 이용해보면 어떨까 싶었습니다.
```suggestion
// constants/index.js
const default = {
  startedAt: null,
  endedat: null,
  lat: null,
  ..
  isPublic: false
}

//함수 선언부
function validate(key, value) {
  if(key === 'lng'){
    return typeof value === "number" && value >= -90 && value <= 90;
  } else if (key==='title'){
    return typeof value === "string";
    }
    ..
}

//router.post 내부
object.entries(req.body).forEach((key, value)=>{
   if(!validate(key, value)) req.body[key] = default[key]
})
}

const { title, importance, startedAt, endedAt, lat, lng, isPublic, tagIdx, content, done, date, labels } = req.body;
```

2022-11-27 17:22 UTC, sooyeon73 reviewed
수고하셨습니다!! task가 가장 주요 요소인만큼 꼼꼼히 validate 해주셔서 정말 좋은 것 같습니다 👏
프론트에서 form 데이터 유효성 검증 라이브러리를 사용했던 것 처럼 백 단에도 비슷한 게 있지 않을까하고 찾아봤는데 [express-validator](https://www.npmjs.com/package/express-validator) 라는 라이브러리가 있네요 ( 다운로드 수는 form hook에 비하면 많이 낮습니다 ㅎㅎ ) 혹시 관심 있으시면 나중에 참고하시라고 달아놓습니다!

2022-11-27 17:22 UTC, sooyeon73 commented on server/src/api/task.ts
> +  if (!validateTime(endedAt)) endedAt = null;
startedAt endedAt 은 필수요소로 생각해야 되지 않을까 싶은데 어떤가요??

2022-11-28 04:51 UTC, mikaniz approved these changes

2022-11-28 05:24 UTC, high2092 commented on server/src/api/task.ts
> +  if (!validateLabels(labels)) labels = [];
피드백 반영했습니다! 감사합니다.
https://github.com/boostcampwm-2022/web19-Boostart/pull/89/commits/2e6ddfbc627c132069d1d68ba72498576552c1b5

2022-11-28 05:30 UTC, high2092 commented on server/src/api/task.ts
> +  if (!validateTime(endedAt)) endedAt = null;
피드백 반영했습니다! 감사합니다.
사용자가 시작 시각과 종료 시각을 설정하지 않은 경우,
요청에는 현재 시각이 기본값으로 들어가도록 하면 좋을 것 같습니다.
https://github.com/boostcampwm-2022/web19-Boostart/pull/89/commits/8817170af38278923f789d20e56fd3f658a949e2

2022-11-28 06:01 UTC, sooyeon73 approved these changes

2022-11-28 06:50 UTC, ParkKyungChan approved these changes

2022-11-28 07:20 UTC, merged