[BE] [7-27] task 완료 API
boostcampwm-2022/web19-Boostart pull request #90
Opened 2022-11-26 14:18 UTC by high2092

## 요약
사용자가 요청을 통해 자신의 task의 완료 여부를 `false`에서 `true`로 변경할 수 있습니다.

## 테스트 방법
1. 로그인을 완료하세요.
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/task/18', {
  method: 'PATCH',
  credentials: 'include',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    done: true,
  }),
}).then((res) => {
  if (res.ok) console.log('GOOD');
});
```
- body가 잘못된 경우 → 400
  - done 이외의 필드가 포함된 경우
  - done 필드의 값을 `false`로 설정한 경우
  - done 필드가 포함되지 않은 경우
- 이미 해당 task가 완료 상태인 경우 → 409
- 자신의 task가 아닌 경우 → 403
- 요청한 task가 존재하지 않는 경우 → 404

2022-11-27 10:17 UTC, ParkKyungChan approved these changes
수고하셨습니다

2022-11-27 17:26 UTC, sooyeon73 commented
수고하셨습니다! 미완료된 task를 완료시키는 방향만 존재해도 될 지 스크럼 때 한 번 얘기해봐도 좋을 것 같아욤!!

2022-11-28 04:54 UTC, mikaniz commented on server/src/api/task.ts
> +    await executeSql('update task set done = true where idx = ?', [taskIdx]);
스프린트 시간에 논의한 대로 `태스크를 완료 상태로 변경하는 것`이 아니라 `태스크의 상태를 변경하는 것`으로 수정해주시면 감사하겠습니다!

2022-11-28 04:55 UTC, mikaniz requested changes
아래 내용 반영해주시면 감사하겠습니다

2022-11-28 05:59 UTC, mikaniz approved these changes

2022-11-28 06:05 UTC, merged